const $=s=>document.querySelector(s), form=$('#form'), canvas=$('#scene'), ctx=canvas.getContext('2d');
const presets={red:{scene_id:'demo_red_light',ego_speed:13,speed_limit:13.9,lead_distance:32,lead_speed:7,traffic_light:'red',stopline_distance:16,pedestrian_distance:45,road_curvature:.015,route_command:'straight',weather:'clear'},ped:{scene_id:'demo_pedestrian',ego_speed:11,speed_limit:13.9,lead_distance:40,lead_speed:10,traffic_light:'green',stopline_distance:30,pedestrian_distance:11,road_curvature:.01,route_command:'straight',weather:'clear'},lead:{scene_id:'demo_lead_vehicle',ego_speed:14,speed_limit:16.7,lead_distance:9,lead_speed:4,traffic_light:'green',stopline_distance:42,pedestrian_distance:50,road_curvature:.008,route_command:'straight',weather:'clear'},curve:{scene_id:'demo_rainy_curve',ego_speed:13,speed_limit:13.9,lead_distance:38,lead_speed:10,traffic_light:'green',stopline_distance:40,pedestrian_distance:48,road_curvature:.085,route_command:'left',weather:'night'}};
let data=null, frame=0, playing=true, last=0;
let activeScene='demo_red_light';
function formData(){const o=Object.fromEntries(new FormData(form));['ego_speed','speed_limit','lead_distance','lead_speed','stopline_distance','pedestrian_distance','road_curvature'].forEach(k=>o[k]=+o[k]);o.scene_id=activeScene;return o}
function setPreset(name){activeScene=presets[name].scene_id;Object.entries(presets[name]).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v});document.querySelectorAll('#presets button').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));run()}
document.querySelectorAll('#presets button').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));
async function run(){const btn=$('#run');btn.disabled=true;btn.textContent='正在生成双策略轨迹…';try{const r=await fetch('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formData())});const d=await r.json();if(!r.ok||d.error)throw Error(d.error||'服务响应失败');data=d;frame=0;playing=true;renderPanels();draw();}catch(e){const box=$('#error');box.textContent=e.message;box.style.display='block';setTimeout(()=>box.style.display='none',3500)}finally{btn.disabled=false;btn.textContent='运行 Critic → Reflection → 重规划'}}
function renderPanels(){const sel=data.selected_policy,b=data.results.baseline,n=data.results[sel],c=n.critic,r=b.reflection,m=data.model,bm=b.model,nm=n.model;$('#baseOverall').textContent=b.critic.overall_score.toFixed(1);$('#newOverall').textContent=c.overall_score.toFixed(1);$('#baseTarget').textContent=b.trajectory.target_speed.toFixed(1)+' m/s';$('#newTarget').textContent=n.trajectory.target_speed.toFixed(1)+' m/s';$('#baseFailures').textContent=b.critic.failures.length?b.critic.failures.length+' 项':'0 项';$('#decision').textContent=data.delta.target_speed<-.2?'减速修正':data.delta.target_speed>.2?'加速修正':'保持策略';$('#delta').textContent=(data.delta.overall>=0?'+':'')+data.delta.overall.toFixed(1)+' 综合分';const scores=[['Safety',c.safety_score],['Rule',c.rule_score],['Comfort',c.comfort_score],['Overall',c.overall_score]];$('#scores').innerHTML=scores.map(([k,v])=>`<div class="score"><span>${k}</span><strong>${v.toFixed(1)}</strong><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');$('#timeline').innerHTML=data.events.map((e,i)=>`<div class="event ${i===0?'active':''}"><b>${String(i+1).padStart(2,'0')} · ${e.phase}</b><p>${esc(e.detail)}</p></div>`).join('');const hist=data.evolution_history||[];$('#evolution').innerHTML=hist.length?hist.map((e,i)=>`<div class="event ${i===hist.length-1?'active':''}"><b>Round ${e.round} · 综合分 ${e.mean_overall.toFixed(1)}</b><p>反思 ${e.revised_samples} 条 · 失败事件 ${e.failure_events} · 记忆池 ${e.memory_size}</p></div>`).join(''):'<div class="empty">尚未运行本地自进化训练。</div>';$('#reflection').innerHTML=`<span class="verdict">${r.verdict==='revise'?'需要修正':'轨迹可接受'}</span><h3>根因</h3>${list(r.root_causes)}<h3>证据</h3>${list(r.evidence)}<h3>纠正策略</h3>${list(r.corrective_strategy)}<h3>反事实动作</h3><ul><li>${esc(r.counterfactual_action)}</li></ul>`;const real=bm.runtime_mode==='opendrivevla_cache'||nm.runtime_mode==='opendrivevla_cache';$('#runtimePill').innerHTML=`<i></i>${real?'含 OpenDriveVLA 真实缓存':'CPU 回退模式'}`;$('#model').innerHTML=`<strong>OpenDriveVLA-0.5B · ${m.checkpoint_installed?'checkpoint 已核验':'checkpoint 不完整'}</strong>Baseline：${esc(bm.runtime)}<br>${sel}：${esc(nm.runtime)}<br>自进化：${hist.length} 轮 · ${hist.length?hist[hist.length-1].memory_size:0} 条反思记忆<br>${esc(m.disclosure)}`}
function list(a){return a&&a.length?'<ul>'+a.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':'<p class="empty">无硬约束失败</p>'}function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function roadPoint(p){const scale=8.2,center=canvas.width/2;return{x:center+p[1]*30,y:canvas.height-42-p[0]*scale}}
function rounded(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function drawRoad(s){const w=canvas.width,h=canvas.height;ctx.fillStyle=s.weather==='night'?'#06101a':'#101b25';ctx.fillRect(0,0,w,h);for(let i=0;i<70;i++){const x=(i*83)%w,y=(i*47)%h;ctx.fillStyle=i%3?'#122436':'#173044';ctx.fillRect(x,y,2,2)}ctx.save();ctx.translate(w/2,0);ctx.rotate(-s.road_curvature*.9);ctx.fillStyle='#27313b';ctx.fillRect(-150,-80,300,h+180);ctx.fillStyle='#131d27';ctx.fillRect(-160,-80,10,h+180);ctx.fillRect(150,-80,10,h+180);ctx.setLineDash([22,22]);ctx.strokeStyle='#d7dee877';ctx.lineWidth=2;[-50,50].forEach(x=>{ctx.beginPath();ctx.moveTo(x,-80);ctx.lineTo(x,h+80);ctx.stroke()});ctx.setLineDash([]);ctx.restore();const stop=roadPoint([s.stopline_distance,0]);ctx.fillStyle='#f5f7fa';ctx.fillRect(w/2-142,stop.y-4,284,8);for(let i=-4;i<=4;i+=2){ctx.fillStyle='#d9e0e7';ctx.fillRect(w/2+i*22-17,stop.y-48,34,8)}const lightY=Math.max(50,stop.y-28);rounded(w/2+172,lightY-28,22,61,7,'#172331');ctx.fillStyle=s.traffic_light==='red'?'#ff5268':'#2d453e';ctx.beginPath();ctx.arc(w/2+183,lightY-14,6,0,7);ctx.fill();ctx.fillStyle=s.traffic_light==='green'?'#4ee398':'#29463e';ctx.beginPath();ctx.arc(w/2+183,lightY+17,6,0,7);ctx.fill();const lead=roadPoint([s.lead_distance,0]);car(lead.x-14,lead.y-25,'#d98b37',0);if(s.pedestrian_distance<55){const ped=roadPoint([s.pedestrian_distance,-2.5]);ctx.fillStyle='#ffd56a';ctx.beginPath();ctx.arc(ped.x,ped.y-7,5,0,7);ctx.fill();ctx.strokeStyle='#ffd56a';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(ped.x,ped.y-1);ctx.lineTo(ped.x,ped.y+12);ctx.moveTo(ped.x,ped.y+4);ctx.lineTo(ped.x-7,ped.y+9);ctx.moveTo(ped.x,ped.y+4);ctx.lineTo(ped.x+7,ped.y+9);ctx.stroke()}if(s.weather==='rain'){ctx.strokeStyle='#6da5d455';ctx.lineWidth=1;for(let i=0;i<45;i++){let x=(i*71)%w,y=(i*43)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+17);ctx.stroke()}}}
function car(x,y,color,angle=0){ctx.save();ctx.translate(x+14,y+25);ctx.rotate(angle);rounded(-14,-25,28,50,7,color);ctx.fillStyle='#9ed5ec';ctx.fillRect(-9,-14,18,10);ctx.fillStyle='#111a22';ctx.fillRect(-9,10,18,8);ctx.restore()}
function path(points,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();points.forEach((p,i)=>{const q=roadPoint(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke();points.forEach((p,i)=>{if(i%2)return;const q=roadPoint(p);ctx.fillStyle=color;ctx.beginPath();ctx.arc(q.x,q.y,2.4,0,7);ctx.fill()})}
function draw(){if(!data)return;const s=data.scenario,b=data.results.baseline.trajectory.points,n=data.results[data.selected_policy].trajectory.points;drawRoad(s);path(b,'#ff6376',3);path(n,'#35d8d0',4);const idx=Math.min(n.length-1,Math.floor(frame));const p=roadPoint(n[idx]),next=roadPoint(n[Math.min(idx+1,n.length-1)]);car(p.x-14,p.y-25,'#35d8d0',Math.atan2(next.y-p.y,next.x-p.x)+Math.PI/2);$('#hudSpeed').innerHTML=n[idx][2].toFixed(1)+' <small>m/s</small>';$('#progress').style.width=(frame/(n.length-1)*100)+'%';const active=Math.min(4,Math.floor(frame/(n.length-1)*5));document.querySelectorAll('.event').forEach((e,i)=>e.classList.toggle('active',i<=active))}
function tick(t){if(data&&playing&&t-last>150){frame+=.32;if(frame>=data.results[data.selected_policy].trajectory.points.length-1){frame=data.results[data.selected_policy].trajectory.points.length-1;playing=false;$('#play').textContent='▶'}draw();last=t}requestAnimationFrame(tick)}
$('#play').onclick=()=>{playing=!playing;const n=data?data.results[data.selected_policy].trajectory.points.length:1;if(frame>=n-1&&playing)frame=0;$('#play').textContent=playing?'Ⅱ':'▶'};$('#reset').onclick=()=>{frame=0;playing=false;$('#play').textContent='▶';draw()};form.onsubmit=e=>{e.preventDefault();run()};
fetch('/api/meta').then(r=>r.json()).then(d=>{const a=d.audit;$('#checkpointPill').innerHTML=`<i></i>${a.checkpoint_installed&&a.code_complete?'基座文件完整':'基座文件待补'}`;$('#model').innerHTML=`<strong>OpenDriveVLA-0.5B · ${a.checkpoint_installed?'checkpoint 已核验':'checkpoint 不完整'}</strong>官方代码：${a.code_complete?'完整':'不完整'} · GPU 依赖：${a.runtime_ready?'就绪':'当前环境未安装'}<br>真实缓存：${a.cache_available?'可用，将优先回放':'尚无，自动回退 CPU'}`}).catch(()=>{});run();requestAnimationFrame(tick);
